name:                BulletProofs
version:             0.1.0.0
github:              "albacorelabs/BulletProofs"
license:             BSD3
author:              "Albacore Labs"
maintainer:          "team@albacore.com"
copyright:           "2019 Albacore Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BulletProofs#readme>

dependencies:
- base >= 4.7 && < 5
- cryptonite
- bytestring
- memory

library:
  source-dirs: src

tests:
  BulletProofs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BulletProofs
    - QuickCheck
    - hspec
    - hspec-core

benchmarks:
  BulletProofs-benchmarks:
    main:                Benchmarks.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Werror
    dependencies:
    - gauge
    - QuickCheck
    - BulletProofs
